file_format: "1"
id: charybdis_nano35
name: Charybdis Nano35
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - keys
  - pointer
  - underglow
siblings:
  - charybdis_nano35_left
  - charybdis_nano35_right
